test_users = [
        {
            'fio': 'Воронов Никита Рустамович',
            'login': 'voronovnr',
            'password': '12#$zxcv',
            'telegram': '@voronovnr',
            'email': 'voronovnr_1@mail.ru',
            'phone': '',
            'group_name': 'КВБО-31-24',
            'birth_date': '2006-12-18',
            'access_level': 'админ',
            'rating': 0,
            'attendance': 0,
            'achievements': ''
        },
        {
            'fio': 'Бельданова Анна Владиславовна',
            'login': 'beldanova',
            'password': 'Bel1432a...',
            'telegram': '@annabeldanova',
            'email': '',
            'phone': '',
            'group_name': '',
            'birth_date': '',
            'access_level': 'админ',
            'rating': 0,
            'attendance': 0,
            'achievements': ''
        },
        {
            'fio': 'Божко Георигий Вадимович',
            'login': 'bojko',
            'password': 'GeorgiBV%1101',
            'telegram': '@GeorgyiBozhko',
            'email': '',
            'phone': '',
            'group_name': '',
            'birth_date': '',
            'access_level': 'админ',
            'rating': 0,
            'attendance': 0,
            'achievements': ''
        },
        {
            'fio': 'Салаватуллина Алия Азатовна',
            'login': 'salavatullina',
            'password': 'SAA^020304',
            'telegram': '@a1iiiia',
            'email': '',
            'phone': '',
            'group_name': '',
            'birth_date': '',
            'access_level': 'админ',
            'rating': 0,
            'attendance': 0,
            'achievements': ''
        },
        {
            'fio': 'Кипреев Леонид Анатольевич',
            'login': 'kipreev',
            'password': 'leo777ka!',
            'telegram': '@lkipreev',
            'email': '',
            'phone': '',
            'group_name': '',
            'birth_date': '',
            'access_level': 'админ',
            'rating': 0,
            'attendance': 0,
            'achievements': ''
        },
        {
            'fio': 'Леонов Даниил Алексеевич',
            'login': 'leonov',
            'password': 'LeonLeon17',
            'telegram': '@darbet17',
            'email': '',
            'phone': '',
            'group_name': '',
            'birth_date': '',
            'access_level': 'админ',
            'rating': 0,
            'attendance': 0,
            'achievements': ''
        },
        {
            'fio': 'Мансуров Руслан Шамильевич',
            'login': 'mansurov',
            'password': 'rus_sham2025',
            'telegram': '@ne_bot_13',
            'email': '',
            'phone': '',
            'group_name': '',
            'birth_date': '',
            'access_level': 'куратор',
            'rating': 0,
            'attendance': 0,
            'achievements': ''
        },
        {
            "fio": "Кожечкина Дарья",
            "login": "kojechkina",
            "password": "daria2025",
            "telegram": "@Misislimonchik",
            "email": "",
            "phone": "",
            "group_name": "",
            "birth_date": "",
            "access_level": "админ",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Ашурков Станислав",
            "login": "ashurkov",
            "password": "stanislav2025",
            "telegram": "@prosto_stas30",
            "email": "",
            "phone": "",
            "group_name": "",
            "birth_date": "",
            "access_level": "куратор",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Воропаева Екатерина",
            "login": "voropaeva",
            "password": "ekaterina2025",
            "telegram": "@Katherine_5",
            "email": "",
            "phone": "",
            "group_name": "",
            "birth_date": "",
            "access_level": "куратор",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Александр Наумов",
            "login": "naumov",
            "password": "aleksandr2025",
            "telegram": "@dat4es",
            "email": "",
            "phone": "",
            "group_name": "",
            "birth_date": "",
            "access_level": "куратор",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Баньщиков Николай Дмитриевич",
            "login": "banshchikov",
            "password": "nikolai2025",
            "telegram": "@Bert1lak",
            "email": "",
            "phone": "",
            "group_name": "ЭЛБО-01-23",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Богатырева Мария Алексеевна",
            "login": "bogatyreva",
            "password": "maria2025",
            "telegram": "@marstsv",
            "email": "",
            "phone": "",
            "group_name": "ХЕБО-01-23",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Голикова Татьяна Владимировна",
            "login": "golikova",
            "password": "tatyana2025",
            "telegram": "@chifeax",
            "email": "",
            "phone": "",
            "group_name": "БСБО-25-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Горбачева Юлия Павловна",
            "login": "gorbacheva",
            "password": "yuliya2025",
            "telegram": "@yuliyaenot",
            "email": "",
            "phone": "",
            "group_name": "КТСО-12-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Дурдыева Нязли",
            "login": "durdyyeva",
            "password": "nyazli2025",
            "telegram": "@qwiebly",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-63-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Загорский Глеб Станиславович",
            "login": "zagorskiy",
            "password": "gleb2025",
            "telegram": "@Dazdir",
            "email": "",
            "phone": "",
            "group_name": "БСБО-42-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Карпук Дарья Романовна",
            "login": "karpuk",
            "password": "darya2025",
            "telegram": "@darya_kpk",
            "email": "",
            "phone": "",
            "group_name": "ТКБО-01-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Кирьянова Наталия Павловна",
            "login": "kiryianova",
            "password": "nataliya2025",
            "telegram": "@kntrsvv",
            "email": "",
            "phone": "",
            "group_name": "ХХБО-03-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Киселев Павел Евгеньевич",
            "login": "kiselev",
            "password": "pavel2025",
            "telegram": "@learned_to_fly",
            "email": "",
            "phone": "",
            "group_name": "ТШБО-01-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Комарова Алёна Евгеньевна",
            "login": "komarova",
            "password": "AlenaKE_25!",
            "telegram": "@wixxb",
            "email": "",
            "phone": "",
            "group_name": "ХХБО-01-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Коновалова Ирина Викторовна",
            "login": "konovalova",
            "password": "IrinaKV_25@",
            "telegram": "@galores3008",
            "email": "",
            "phone": "",
            "group_name": "ХЕБО-05-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Курилов Андрей Игоревич",
            "login": "kurilov",
            "password": "AndreiKI_25#",
            "telegram": "@partycorn",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-18-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Молодняк Алиса Александровна",
            "login": "molodnyak",
            "password": "AlisaMA_25$",
            "telegram": "@xxellyx",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-63-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Нуждин Максим Владимирович",
            "login": "nuzhdin",
            "password": "MaximNV_25%",
            "telegram": "@d1fficult12",
            "email": "",
            "phone": "",
            "group_name": "КРБО-21-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Овечкин Вячеслав Максимович",
            "login": "ovechkin",
            "password": "VyacheslavOM_25^",
            "telegram": "@Slitock",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-42-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Паршинская Таисия Михайловна",
            "login": "parshinskaya",
            "password": "TaisiaPM_25&",
            "telegram": "@umka_tpm",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-30-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Покровская Полина Сергеевна",
            "login": "pokrovskaya",
            "password": "PolinaPS_25*",
            "telegram": "@hhyhmihhy",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-14-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Полянская Яна Сергеевна",
            "login": "polyanskaya",
            "password": "YanaPS_25(",
            "telegram": "@SweetTea_T",
            "email": "",
            "phone": "",
            "group_name": "БСБО-43-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Резанов Савва Владимирович",
            "login": "rezanov",
            "password": "SavvaRV_25)",
            "telegram": "@bigPITON777",
            "email": "",
            "phone": "",
            "group_name": "ИВБО-12-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Сицко Егор Андреевич",
            "login": "sitsko",
            "password": "EgorSA_25_",
            "telegram": "@Seldireie",
            "email": "",
            "phone": "",
            "group_name": "ХХБО-08-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Стрельцова Анастасия Сергеевна",
            "login": "streltssova",
            "password": "AnastasiaSS_25+",
            "telegram": "@m_am0ur",
            "email": "",
            "phone": "",
            "group_name": "ТКБО-03-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Сыван Катерина Денисовна",
            "login": "syvan",
            "password": "KaterinaSD_24!",
            "telegram": "@bxjzonk",
            "email": "",
            "phone": "",
            "group_name": "ХХБО-04-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Толоконникова Милана Алексеевна",
            "login": "tolokonnikova",
            "password": "MilanaTA_25@",
            "telegram": "@minulana18",
            "email": "",
            "phone": "",
            "group_name": "РГБО-01-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Ульев Андрей Александрович",
            "login": "ulyev",
            "password": "AndreiUA_25#",
            "telegram": "@APostel",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-63-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Юрьева Валерия Игоревна",
            "login": "yuryeva",
            "password": "ValeriaYI_25$",
            "telegram": "@lerrrrhx",
            "email": "",
            "phone": "",
            "group_name": "УНБО-06-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Яскевич Даниил Михайлович",
            "login": "yaskevich",
            "password": "DaniilYM_25%",
            "telegram": "@danyasx",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-42-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Авдеев Андрей Максимович",
            "login": "avdeev",
            "password": "AndreiAM_25!",
            "telegram": "@White_Shark_053",
            "email": "",
            "phone": "",
            "group_name": "БИСО-03-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Берендеева Олеся Константиновна",
            "login": "berendeeva",
            "password": "OlesyaBK_24@",
            "telegram": "@lesia1504",
            "email": "",
            "phone": "",
            "group_name": "ХББО-02-24",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Близниченко Иван Алексеевич",
            "login": "bliznichenko",
            "password": "IvanBA_25#",
            "telegram": "@ivan_bliznichenko",
            "email": "",
            "phone": "",
            "group_name": "ИМБО-10-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Ванина Полина Алексеевна",
            "login": "vanina",
            "password": "PolinaVA_25$",
            "telegram": "@ljivvv",
            "email": "",
            "phone": "",
            "group_name": "ИМБО-10-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Вербовец Вероника Андреевна",
            "login": "verbovets",
            "password": "VeronikaVA_25%",
            "telegram": "@nikismiti",
            "email": "",
            "phone": "",
            "group_name": "ХХБО-01-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Гаврилюк Максим",
            "login": "gavrilyuk",
            "password": "MaximG_25^",
            "telegram": "@mapk9g",
            "email": "",
            "phone": "",
            "group_name": "ИВБО-10-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Громадина Юлия Николаевна",
            "login": "gromadina",
            "password": "YuliyaGN_25&",
            "telegram": "@Ulia_grm",
            "email": "",
            "phone": "",
            "group_name": "ИНБО-11-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Губина Василиса Андреевна",
            "login": "gubina",
            "password": "VasilisaGA_25*",
            "telegram": "@xpamcna",
            "email": "",
            "phone": "",
            "group_name": "БФБО-07-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Демина Мария Николаевна",
            "login": "demina",
            "password": "MariaDN_25(",
            "telegram": "@romlissss",
            "email": "",
            "phone": "",
            "group_name": "ИНБО-11-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Докукин Дмитрий Алексеевич",
            "login": "dokukin",
            "password": "DmitriyDA_25)",
            "telegram": "@lmndk",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-42-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Журавова Ангелина Сергеевна",
            "login": "zhuravova",
            "password": "AngelinaZS_25_",
            "telegram": "@McLoch",
            "email": "",
            "phone": "",
            "group_name": "БФБО-07-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Корлякова Юлия Сергеевна",
            "login": "korlyakova",
            "password": "YuliyaKS_25+",
            "telegram": "@Yulik2",
            "email": "",
            "phone": "",
            "group_name": "ИМБО-10-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Корсунский Максим Андреевич",
            "login": "korsunskiy",
            "password": "MaximKA_25!",
            "telegram": "@maxkors2d",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-63-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Куликова Екатерина Сергеевна",
            "login": "kulikova",
            "password": "EkaterinaKS_23@",
            "telegram": "@Kulich0k",
            "email": "",
            "phone": "",
            "group_name": "БСБО-03-23",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Лобацевич Алиса Алексеевна",
            "login": "lobatsevich",
            "password": "AlisaLA_25#",
            "telegram": "@allo8che",
            "email": "",
            "phone": "",
            "group_name": "ХББО-07-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Маликова Юлия Александровна",
            "login": "malikova",
            "password": "YuliyaMA_25$",
            "telegram": "@jj_malikan",
            "email": "",
            "phone": "",
            "group_name": "БФБО-06-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Марьин Михаил Вячеславович",
            "login": "marin",
            "password": "MikhailMV_24%",
            "telegram": "@m5hmarin",
            "email": "",
            "phone": "",
            "group_name": "РКБО-01-24",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Митрофанова Валерия Денисовна",
            "login": "mitrofanova",
            "password": "ValeriaMD_25^",
            "telegram": "@mitrolerka",
            "email": "",
            "phone": "",
            "group_name": "УНБО-06-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Рогозинский Иван Николаевич",
            "login": "rogozinskiy",
            "password": "IvanRN_25&",
            "telegram": "@Zubrrrrrrrrrrrrrr",
            "email": "",
            "phone": "",
            "group_name": "ИМБО-10-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Сапунихин Денис Павлович",
            "login": "sapunihin",
            "password": "DenisSP_25*",
            "telegram": "@Denis_Poseidon",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-63-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Сидорова Юлия Дмитриевна",
            "login": "sidorova",
            "password": "YuliyaSD_25(",
            "telegram": "@hionxf",
            "email": "",
            "phone": "",
            "group_name": "ЭФБО-08-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Тагиев Джарислан Этибарович",
            "login": "tagiev",
            "password": "DzharyslanTE_25)",
            "telegram": "@qqqaalll",
            "email": "",
            "phone": "",
            "group_name": "УУБО-04-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Шарова Вероника Витальевна",
            "login": "sharova",
            "password": "VeronikaSV_25_",
            "telegram": "@mvrnkaa",
            "email": "",
            "phone": "",
            "group_name": "КСБО-11-25",
            "birth_date": "",
            "access_level": "боец",
                            "rating": 0,
                            "attendance": 0,
                            "achievements": ""
        },
        {
            "fio": "Бобринский Вадим Денисович",
            "login": "bobrinskiy",
            "password": "bobrinskiyim!@#1",
            "telegram": "@kukychl",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-42-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Бойченцев Матвей Константинович",
            "login": "boychentsev",
            "password": "boychentsevyw!@#2",
            "telegram": "@matveyywe",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-64-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Бородина Алина Сергеевна",
            "login": "borodina",
            "password": "borodinana!@#3",
            "telegram": "@Alinaa_bs",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-63-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Будаев Николай Владимирович",
            "login": "budaev",
            "password": "budaevly!@#4",
            "telegram": "@Lubluluto",
            "email": "",
            "phone": "",
            "group_name": "ККСО-24-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Ветошкина Варвара Викторовна",
            "login": "vetoshkina",
            "password": "vetoshkinaar!@#5",
            "telegram": "@vrvtshkn",
            "email": "",
            "phone": "",
            "group_name": "ХХБО-03-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Власова Дарья Сергеевна",
            "login": "vlasova",
            "password": "vlasovaya!@#6",
            "telegram": "@mivdeks",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-50-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Дрожникова Дарья Александровна",
            "login": "drozhnikova",
            "password": "drozhnikovaya!@#7",
            "telegram": "@kuki_hot",
            "email": "",
            "phone": "",
            "group_name": "РГБО-01-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Захарова Евгения Александровна",
            "login": "zakharova",
            "password": "zakharovaya!@#8",
            "telegram": "@seishouu",
            "email": "",
            "phone": "",
            "group_name": "ХЕБО-01-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Калинин Михаил Юрьевич",
            "login": "kalinin",
            "password": "kalininingl!@#9",
            "telegram": "@KALININ_MK",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-63-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Кислов Ярослав Павлович",
            "login": "kislov",
            "password": "kislovav!@#10",
            "telegram": "@techn2412",
            "email": "",
            "phone": "",
            "group_name": "КАБО-11-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Коротков Владислав Сергеевич",
            "login": "korotkov",
            "password": "korotkovav!@#11",
            "telegram": "@Gelmgoltz",
            "email": "",
            "phone": "",
            "group_name": "КАМО-01-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Крейш Георгий Эльвирович",
            "login": "kreish",
            "password": "kreishiy!@#12",
            "telegram": "@goshanya_s",
            "email": "",
            "phone": "",
            "group_name": "ТХБО-01-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Кузина Татьяна Юрьевна",
            "login": "kuzina",
            "password": "kuzinaana!@#13",
            "telegram": "@tmeellko",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-42-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Мальцев Эгдар Юрьевич",
            "login": "maltsev",
            "password": "maltsevdr!@#14",
            "telegram": "@joihanness",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-63-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Мартыновская Ангелина Александровна",
            "login": "martynovskaya",
            "password": "martynovskayaia!@#15",
            "telegram": "@rihitose02",
            "email": "",
            "phone": "",
            "group_name": "ТКБО-01-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Мискаров Игорь Юрьевич",
            "login": "miskarov",
            "password": "miskarovyh!@#16",
            "telegram": "@xaxadura",
            "email": "",
            "phone": "",
            "group_name": "БФБО-08-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Родионова Ксения Денисовна",
            "login": "rodionova",
            "password": "rodionovaye!@#17",
            "telegram": "@loxyushka",
            "email": "",
            "phone": "",
            "group_name": "ХББО-05-23",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Рукинов Тимофей Алексеевич",
            "login": "rukinov",
            "password": "rukinovey!@#18",
            "telegram": "@lelaksi",
            "email": "",
            "phone": "",
            "group_name": "ИВБО-20-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Румынина Екатерина Дмитриевна",
            "login": "rumynina",
            "password": "rumyninana!@#19",
            "telegram": "@SweetFox2",
            "email": "",
            "phone": "",
            "group_name": "БИСО-02-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Рябченко Александр Максимович",
            "login": "ryabchenko",
            "password": "ryabchenkoko!@#20",
            "telegram": "@Blosfora",
            "email": "",
            "phone": "",
            "group_name": "БАСО-01-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Сидоров Иван Олегович",
            "login": "sidorov",
            "password": "sidorovan!@#21",
            "telegram": "@FADETOBLACK84",
            "email": "",
            "phone": "",
            "group_name": "РКБО-03-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Симоненко Илья Александрович",
            "login": "simonenko",
            "password": "simonenkoia!@#22",
            "telegram": "@ilsimn",
            "email": "",
            "phone": "",
            "group_name": "ЭЛБО-01-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Соломенко Дарина Витальевна",
            "login": "solomenko",
            "password": "solomenkova!@#23",
            "telegram": "@princessedesanges",
            "email": "",
            "phone": "",
            "group_name": "ХЕБО-03-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Черваков Кирилл Борисович",
            "login": "chervakov",
            "password": "chervakovll!@#24",
            "telegram": "@k1ronchic",
            "email": "",
            "phone": "",
            "group_name": "ИНБО-11-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Сурин Саша",
            "login": "surin",
            "password": "surinna!@#25",
            "telegram": "",
            "email": "",
            "phone": "",
            "group_name": "",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Аблазова Оксана Богдановна",
            "login": "ablazova",
            "password": "ablazovaok@25",
            "telegram": "@kamenskyy",
            "email": "",
            "phone": "",
            "group_name": "БАСО-03-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Афанасьева Диана Дмитриевна",
            "login": "afanasyeva",
            "password": "afanasyevadi@25",
            "telegram": "@itsdianafaiiry",
            "email": "",
            "phone": "",
            "group_name": "ХХБО-03-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Батырбеков Ыйман Адилетович",
            "login": "batyrbekov",
            "password": "batyrbekovyy@25",
            "telegram": "@YimanRB",
            "email": "",
            "phone": "",
            "group_name": "ЭПБО-02-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Васильева Кристина Игоревна",
            "login": "vasilieva",
            "password": "vasilievakr@25",
            "telegram": "@kris_vasilyeva",
            "email": "",
            "phone": "",
            "group_name": "ТКБО-01-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Вахобова Марзияхон Абдухамидовна",
            "login": "vahobova",
            "password": "vahobovama@25",
            "telegram": "@ma_rzipan",
            "email": "",
            "phone": "",
            "group_name": "ХЕБО-03-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Веселова Елизавета Романовна",
            "login": "veselova",
            "password": "veselovael@25",
            "telegram": "@LizaJoy7",
            "email": "",
            "phone": "",
            "group_name": "ХХБО-03-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Габаев Егор Александрович",
            "login": "gabaev",
            "password": "gabaeveg@25",
            "telegram": "@DKTulen",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-42-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Гвоздева Ольга Дмитриевна",
            "login": "gvozdeva",
            "password": "gvozdevaol@25",
            "telegram": "@ylinkoloitor_kk",
            "email": "",
            "phone": "",
            "group_name": "ТКБО-02-23",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Деркач Никита Сергеевич",
            "login": "derkach",
            "password": "derkachni@25",
            "telegram": "@Nikitos1280",
            "email": "",
            "phone": "",
            "group_name": "ИНБО-11-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Дружинина Анна Витальевна",
            "login": "druzhinina",
            "password": "druzhininaan@25",
            "telegram": "@annaboutlove",
            "email": "",
            "phone": "",
            "group_name": "ХЕБО-05-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Ермакова Екатерина Юрьевна",
            "login": "ermakova",
            "password": "ermakovaka@25",
            "telegram": "@tehnotelka",
            "email": "",
            "phone": "",
            "group_name": "ХТМО-01-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Климов Сергей Максимович",
            "login": "klimov",
            "password": "klimovse@25",
            "telegram": "@schrodingercry",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-42-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Козлова Анна Андреевна",
            "login": "kozlova",
            "password": "kozlovaan@25",
            "telegram": "@tqotfw",
            "email": "",
            "phone": "",
            "group_name": "КТСО-03-23",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Кук Дарья Сергеевна",
            "login": "kuk",
            "password": "kukda@25",
            "telegram": "@nothingllo",
            "email": "",
            "phone": "",
            "group_name": "ТКБО-02-23",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Лесаев Августин Николаевич",
            "login": "lesaev",
            "password": "lesaevav@25",
            "telegram": "@Sauronct",
            "email": "",
            "phone": "",
            "group_name": "УМБО-01-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Округина Владислава Ильинична",
            "login": "okrugina",
            "password": "okruginavl@25",
            "telegram": "@okdokdokd",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-63-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Панов Иван Дмитриевич",
            "login": "panov",
            "password": "panoviv@25",
            "telegram": "@Busif",
            "email": "",
            "phone": "",
            "group_name": "БСБО-54-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Плахотнюк Даниил Сергеевич",
            "login": "plakhotnyuk",
            "password": "plakhotnyukda@25",
            "telegram": "@danchik272",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-42-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Потапов Иван Дмитриевич",
            "login": "potapov",
            "password": "potapoviv@25",
            "telegram": "@Kwakushe4ka",
            "email": "",
            "phone": "",
            "group_name": "УМБО-01-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Пронина Елизавета Дмитриевна",
            "login": "pronina",
            "password": "proninael@25",
            "telegram": "@chehehemist59",
            "email": "",
            "phone": "",
            "group_name": "ХББО-04-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Пустовалов Богдан Олегович",
            "login": "pustovalov",
            "password": "pustovalovbo@25",
            "telegram": "@BogdanPustovalov",
            "email": "",
            "phone": "",
            "group_name": "КВБО-42-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Руденко София Александровна",
            "login": "rudenko",
            "password": "rudenkoSo@25",
            "telegram": "@LCapusta",
            "email": "",
            "phone": "",
            "group_name": "БАСО-03-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Сморгачев Егор Максимович",
            "login": "smorgachev",
            "password": "smorgacheveg@25",
            "telegram": "@Semdeva",
            "email": "",
            "phone": "",
            "group_name": "ЭФБО-05-23",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Трофимов Виктор Михайлович",
            "login": "trofimov",
            "password": "trofimovvi@25",
            "telegram": "@The_Emperor_of_the_World",
            "email": "",
            "phone": "",
            "group_name": "ККСО-24-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Фёклина Ульяна Андреевна",
            "login": "feklina",
            "password": "feklinaul@25",
            "telegram": "@shetoore4l",
            "email": "",
            "phone": "",
            "group_name": "УМБО-01-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Цех Надежда Алексеевна",
            "login": "tseh",
            "password": "tsehna@25",
            "telegram": "@tse2803",
            "email": "",
            "phone": "",
            "group_name": "ТКБО-01-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Швецова Варвара Аркадьевна",
            "login": "shvetsova",
            "password": "shvetsovava@25",
            "telegram": "@varja_technetium",
            "email": "",
            "phone": "",
            "group_name": "ИНБО-11-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Абрамова Ксения Владимировна",
            "login": "abramova",
            "password": "abramovaks@25",
            "telegram": "@seniavva",
            "email": "",
            "phone": "",
            "group_name": "УНБО-06-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Алексеева Вероника Владимировна",
            "login": "alekseeva",
            "password": "alekseevave@25",
            "telegram": "@lekvver",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-42-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Вертоградов Матвей Олегович",
            "login": "vertogradov",
            "password": "vertogradovma@25",
            "telegram": "@ethereal_myauf",
            "email": "",
            "phone": "",
            "group_name": "БСБО-12-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Волотов Максим Михайлович",
            "login": "volotov",
            "password": "volotovma@25",
            "telegram": "@Duthaegaux",
            "email": "",
            "phone": "",
            "group_name": "ББСО-01-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Ганзюк Анна Викторовна",
            "login": "ganzuyk",
            "password": "ganzuykan@25",
            "telegram": "@AnyaaaaVv",
            "email": "",
            "phone": "",
            "group_name": "ИМБО-10-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Герасимов Иван Игоревич",
            "login": "gerasimov",
            "password": "gerasimoviv@25",
            "telegram": "@ElKovrik",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-21-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Головачев Тихон Романович",
            "login": "golovachev",
            "password": "golovachevti@25",
            "telegram": "@TikhonGolovachev",
            "email": "",
            "phone": "",
            "group_name": "ИНБО-11-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Грабенко Алёна Андреевна",
            "login": "grabenko",
            "password": "grabenkoal@25",
            "telegram": "@aalealen",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-42-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Жигалова Елизавета Евгеньевна",
            "login": "zhigalova",
            "password": "zhigalovael@25",
            "telegram": "@nadoveritvlychee",
            "email": "",
            "phone": "",
            "group_name": "ХББО-06-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Капунцова Варвара Дмитриевна",
            "login": "kapuntsova",
            "password": "kapuntsovava@25",
            "telegram": "@myriro",
            "email": "",
            "phone": "",
            "group_name": "РИБО-02-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Колосов Владислав Игоревич",
            "login": "kolosov",
            "password": "kolosovvl@25",
            "telegram": "@FIADEI",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-63-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Кузнецов Владимир Николаевич",
            "login": "kuznetsov",
            "password": "kuznetsovvl@25",
            "telegram": "@Deidata4554",
            "email": "",
            "phone": "",
            "group_name": "ЭФБО-05-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Кулин Андрей Александрович",
            "login": "kulin",
            "password": "kulinan@25",
            "telegram": "@m1rallq",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-63-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Кухтарова Александра Андреевна",
            "login": "kukhtarova",
            "password": "kukhtarovaal@25",
            "telegram": "@kukhtarova",
            "email": "",
            "phone": "",
            "group_name": "УНБО-01-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Луппова Мария Андреевна",
            "login": "luppova",
            "password": "luppovama@25",
            "telegram": "@konchennaya0",
            "email": "",
            "phone": "",
            "group_name": "ХЕБО-05-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Мамадраимов Роман Шукратович",
            "login": "mamadraimov",
            "password": "mamadraimovro@25",
            "telegram": "@Rostarik",
            "email": "",
            "phone": "",
            "group_name": "ЭЛБО-01-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Михаленко Анастасия Сергеевна",
            "login": "mikhalenko",
            "password": "mikhalenkoan@25",
            "telegram": "@aurora_astri",
            "email": "",
            "phone": "",
            "group_name": "ИКБО-42-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Мошкарина Мария Ивановна",
            "login": "moshkarina",
            "password": "moshkarinama@25",
            "telegram": "@monica_river",
            "email": "",
            "phone": "",
            "group_name": "БФБО-05-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Одоевцев Илья Борисович",
            "login": "odoevtsev",
            "password": "odoevtsevil@25",
            "telegram": "@lnkmstchhh",
            "email": "",
            "phone": "",
            "group_name": "ИНБО-11-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Полина Алексеевна Топорикова",
            "login": "toporikova",
            "password": "toporikovapo@25",
            "telegram": "@teaandcoffee21",
            "email": "",
            "phone": "",
            "group_name": "ХББО-07-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Рожнов Василий Геннадьевич",
            "login": "rozhnov",
            "password": "rozhnovva@25",
            "telegram": "@vasyunea",
            "email": "",
            "phone": "",
            "group_name": "ИНБО-20-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Смирнов Сергей Сергеевич",
            "login": "smirnov",
            "password": "smirnovse@25",
            "telegram": "@Q_st0rmY",
            "email": "",
            "phone": "",
            "group_name": "ЩПКО-04-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Счётчиков Андрей Алексеевич",
            "login": "schetchikov",
            "password": "schetchikovan@25",
            "telegram": "@TheWestX",
            "email": "",
            "phone": "",
            "group_name": "ККСО-01-23",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Черепанов Дмитрий Денисович",
            "login": "cherepanov",
            "password": "cherepanovdm@25",
            "telegram": "@cherepaaaa",
            "email": "",
            "phone": "",
            "group_name": "УИБО-12-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Щивинская Татьяна Алексеевна",
            "login": "shchivinskaya",
            "password": "shchivinskayata@25",
            "telegram": "@Tankashmanka",
            "email": "",
            "phone": "",
            "group_name": "ИМБО-10-25",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        },
        {
            "fio": "Эмухвари Кристина Тимуровна",
            "login": "emukhvari",
            "password": "emukhvarikr@25",
            "telegram": "@JustBurningHeart",
            "email": "",
            "phone": "",
            "group_name": "КМБО-12-24",
            "birth_date": "",
            "access_level": "боец",
            "rating": 0,
            "attendance": 0,
            "achievements": ""
        }
]

import csv

output_file = 'users.csv'

# Поля, которые нужно записать
fields = ['fio', 'login', 'password']

with open(output_file, mode='w', newline='', encoding='utf-8') as file:
    writer = csv.DictWriter(file, fieldnames=fields)
    writer.writeheader()
    for user in test_users:
        # Создаем новый словарь только с нужными ключами, если их нет - ставим пустую строку
        row = {field: user.get(field, '') for field in fields}
        writer.writerow(row)

print(f'Данные сохранены в файл {output_file}')
